# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2018-02-04 07:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=300)),
                ('user', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('promotion_name', models.CharField(max_length=50)),
                ('initial_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('city', models.CharField(max_length=20)),
                ('cost', models.IntegerField()),
                ('description', models.CharField(max_length=300)),
                ('image', models.CharField(max_length=600)),
            ],
        ),
        migrations.AddField(
            model_name='message',
            name='promotion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='promotions.Promotion'),
        ),
    ]
