# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-10 04:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('promotions', '0005_auto_20180210_0423'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={},
        ),
    ]
