# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-10 04:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('promotions', '0006_auto_20180210_0434'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='user',
        ),
    ]
