# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-12 14:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promotions', '0010_auto_20180210_0502'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promotion',
            name='cost',
            field=models.DecimalField(decimal_places=3, max_digits=10),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='category',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='image',
            field=models.ImageField(null=True, upload_to='static/images/profile'),
        ),
    ]
