# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2018-02-14 13:09
from __future__ import unicode_literals

import django.contrib.auth.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0007_alter_validators_add_error_messages'),
        ('promotions', '0012_auto_20180213_1551'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserRegister',
            fields=[
            ],
            options={
                'ordering': ('first_name',),
                'proxy': True,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
