# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2018-02-18 01:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promotions', '0014_userprofile_imageurl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='image',
            field=models.ImageField(null=True, upload_to='/var/www/static/images/profile'),
        ),
    ]
