# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2018-02-18 03:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promotions', '0023_auto_20180217_2229'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='imageUrl',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='image',
            field=models.ImageField(null=True, upload_to='promotions/static/images/profile/'),
        ),
    ]
