# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2018-02-18 20:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('promotions', '0025_auto_20180218_1511'),
    ]

    operations = [
        migrations.AddField(
            model_name='promotion',
            name='ciiudad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='promotions.Cities'),
        ),
    ]
