# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2018-02-18 20:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('promotions', '0026_promotion_ciiudad'),
    ]

    operations = [
        migrations.RenameField(
            model_name='promotion',
            old_name='ciiudad',
            new_name='ciudad',
        ),
    ]
